name: Build and Deploy Nest.js App

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Archive build artifacts
      run: tar -czf build.tar.gz dist

    - name: Copy build to server
      uses: appleboy/scp-action@master
      with:
        host: ${{secrets.SSH_HOST}}
        username: ${{secrets.SSH_USERNAME}}
        password: ${{secrets.SSH_PASSWORD}}
        port: ${{secrets.SSH_PORT}}
        source: "build.tar.gz"
        target: "/var/www/main-backend"

    - name: Deploy on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /var/www/main-backend
          tar -xzf build.tar.gz
          
