name: Deploy Nest.js App

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to server
      env:
        GIT_AUTH: ${{ secrets.AUTH }}
      run: |
        cd /var/www/main-backend/backend-app
        git fetch --all
        git reset --hard origin/master
        git pull origin master
        npm install
        npm run build
        pm2 reload main-backend-app || pm2 start dist/main.js --name main-backend-app
